
<!DOCTYPE HTML>
<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>绑定邮箱</title>
    		
		<link rel="stylesheet" type="text/css" href="/static/home/mobile/css/ydui.css"/>
    <script type="text/javascript" src="/static/home/mobile/js/ydui.flexible.js"></script>
    {include file='common/header'}
    <style>
        body{
            background: #F5F5F5 !important;
        }
    </style>
</head>
<body>

<header class="m-navbar">
    <a href="javascript:history.back()" class="navbar-item">
        <i class="back-ico"></i>
    </a>
    <div class="navbar-center">
        <span class="navbar-title">绑定邮箱</span>
    </div>
    <a href="#" class="navbar-item">
    </a>
</header>
<div class=" bindMail">
<div class="m-cell">
    <div class="cell-item">
        <div class="cell-left">邮箱：</div>
        <div class="cell-right">
        <input type="text" class="cell-input m_txt" placeholder="请输入邮箱账号" id="email" value="{$member['email']?$member['email']:''}" {$member['is_bind_email']?'readonly':''}>
        </div>
    </div>
</div>
    <div class="member-btn">
    <button type="button" class="button1 js-bind"  {$member['is_bind_email']?'disabled':''}>确认</button>
    </div>
</div>
<script type="text/javascript">
    $(function () {
            //设置邮箱
            $('.js-bind').click(function () {
                var email = $('#email').val();
                $.post(
                    window.location.href,
                    {email:email},
                    function (ret) {
                        message(ret.message,ret.redirect,ret.type);
                    },'json'
                );
            });
        });
</script>
</body>
</html>



