
<!DOCTYPE HTML>
<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>资金流水</title>
    {include file='common/header'}
    <link rel="shortcut icon" href="clientapp/images/new_images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="/static/home/mobile/css/ydui.css"/>
        <link rel="stylesheet" href="/static/home/mobile/css/layui.css">
    <script type="text/javascript" src="/static/home/mobile/js/ydui.flexible.js"></script>

    <style>
        body{
            background: #F5F5F5 !important;
        }
    </style>
</head>
<body>

<header class="m-navbar">
    <a href="javascript:history.back()" class="navbar-item">
        <i class="back-ico"></i>
    </a>
    <div class="navbar-center">
        <span class="navbar-title">资金流水</span>
    </div>
    <a href="#" class="navbar-item">
    </a>
</header>
<div class="new-gold-detial">
            
            <div class="new-all-profit">
                您的总收益：<span id="all_profit">{$credit2}</span>元
            </div>
            <div class="update-box mx_list" id="table">
                <ul id="flow">
                </ul>
                <!-- <div class="alipa-box">
                    <div class="task-none" style="display: none;text-align: center;">暂无数据</div>
                </div> -->
            </div>
        </div>
<script type="text/javascript" src="/static/home/mobile/js/layui/layui.js"></script>
<script type="text/javascript">
    $(function(){
                //流加载
                layui.use('flow', function(){
                    var flow = layui.flow;
                    flow.load({
                            elem: '#table'
                            ,done: function(page, next){
                                    var lis = [];
                                    $.get('/home/charge/ajax?page='+page, function(res){
                                        layui.each(res.data.data, function(index, item){
                                                $("#flow").append('<li><b><i>'+item.num+'元</i><time>'+item.create_time+'</time></b><p>'+item.title+'<span>'+item.remark+'</span></p>    </li>');
                                        });
                                        next(lis.join(''), res.data.length > 0 ? true : false);
                                    });
                            }
                    });
                });
        });
</script>
</body>
</html>



