



<!DOCTYPE HTML>
<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>{$item['title']}</title>
		<link rel="shortcut icon" href="clientapp/images/new_images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="/static/home/mobile/css/ydui.css"/>
    <script type="text/javascript" src="/static/home/mobile/js/ydui.flexible.js"></script>

    <style>
        body{
            background: #F5F5F5 !important;
		}
		.new-gold-detial{padding:0.2rem;font-size:0.24rem;}
    </style>
</head>
<body>

<header class="m-navbar">
    <a href="javascript:history.back()" class="navbar-item">
        <i class="back-ico"></i>
    </a>
    <div class="navbar-center">
        <span class="navbar-title">{$item['title']}</span>
    </div>
    <a href="#" class="navbar-item" style="color: #fff;"></a>
</header>
<div class="new-gold-detial">
	{$item['detail']}
</div>
</body>
</html>



