


<!DOCTYPE HTML>
<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>新增反馈</title>
    {include file='common/header'}
		<link rel="shortcut icon" href="clientapp/images/new_images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="/static/home/mobile/css/ydui.css"/>
    <link rel="stylesheet" href="/static/home/mobile/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/home/mobile/css/layui.css">
    <script type="text/javascript" src="/static/home/mobile/js/ydui.flexible.js"></script>
    <style>
        body{
            background: #F5F5F5 !important;
		}
		.new-gold-detial{padding:0.2rem;font-size:0.24rem;}
    </style>
</head>
<body>

<header class="m-navbar">
    <a href="javascript:history.back()" class="navbar-item">
        <i class="back-ico"></i>
    </a>
    <div class="navbar-center">
        <span class="navbar-title">新增反馈</span>
    </div>
    <a href="#" class="navbar-item" ></a>
</header>
<div class=" bindMail" style="padding-top:0.2rem;">
        
        <div class="m-celltitle">反馈填写：</div>
        <div class="m-cell">
            <div class="cell-item">
                <div class="cell-right">
                    <textarea class="cell-textarea" id="content" name="content" placeholder="请输入您需要反馈的内容"></textarea>
                </div>
            </div>
        </div>
        <div class="member-btn">
            <button type="button" class="button1 js-bind"  {$member['is_bind_email']?'disabled':''}>确认</button>
        </div>
       <!--  <div class="member-ts">
            <label>温馨提示</label>
            <p></p>
        </div> -->
    </div>
<script type="text/javascript" src="/static/home/mobile/js/layui/layui.js"></script>
<script type="text/javascript">
 $(function () {
            //设置邮箱
            $('.js-bind').click(function () {
                var content = $('#content').val();
                if ($.trim(content) == "") {
                    message("请输入您需要反馈的内容","","error");
                    return;
                }
                $.post(
                    '/home/feedback/save',
                    {content: content},
                    function (ret) {
                        message(ret.message,ret.redirect,ret.type);
                    },'json'
                );
            });
        });
</script>
</body>
</html>



