



<!DOCTYPE HTML>
<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>我的反馈</title>
    {include file='common/header'}
		<link rel="shortcut icon" href="clientapp/images/new_images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="/static/home/mobile/css/ydui.css"/>
    <script type="text/javascript" src="/static/home/mobile/js/ydui.flexible.js"></script>

    

    <style>
        body{
            background: #F5F5F5 !important;
        }
        .m_textarea{padding:0.1rem 0.2rem;background:#fff;margin:0.2rem 0.2rem;}
        .member-form{background:#fff;margin:0.2rem 0.2rem;border-radius:0.05rem;}
        p{border-bottom:#D9D9D9 solid 1px;padding:0.2rem 0.2rem;display:flex;font-size: 0.24rem;}
        .member-form>p>span{flex:1;text-align:right;}
        .m-celltitle{margin-top:0.5rem;}
    </style>
</head>
<body>

<header class="m-navbar">
    <a href="javascript:history.back()" class="navbar-item">
        <i class="back-ico"></i>
    </a>
    <div class="navbar-center">
        <span class="navbar-title">我的反馈</span>
    </div>
    <a href="#" class="navbar-item" ></a>
</header>
<div class=" bindMail">
        <div class="member-form">
            <p>用户昵称：{$item.username}&nbsp;&nbsp;<span>申请时间：{$item.create_time}</span></p>
            <div class="m_textarea">{$item.content|nl2br}</div>
        </div>
        {if !empty($list)}
        {volist name="list" id="row"}
        <div class="member-form">
            <div class="item-box">
                <div class="m_txt m_txt2">{$row.username?$row.username:'管理回复'}&nbsp;&nbsp;{$row.create_time}</div>
            </div>
            <div class="item-box" style="height: auto;">
                <div class="m_textarea">{$row.content|nl2br}</div>
            </div>
        </div>
        {/volist}
        {/if}
        {$pager}
        <!-- <div class="member-form" style="margin-top: 20px;">
            <div class="item-box" style="height: auto;">
                <textarea id="content" name="content" class="m_textarea" style="height: 160px;" placeholder=""></textarea>
            </div>
        </div> -->
        <div class="m-celltitle">文本域</div>
        <div class="m-cell">
            <div class="cell-item">
                <div class="cell-right">
                    <textarea class="cell-textarea" id="content" name="content" placeholder="请输入您需要回复的内容"></textarea>
                </div>
            </div>
        </div>
        <div class="member-btn">
            {if $item.is_reply == 0}
            <button type="button" class="button1">等待管理员回复</button>
            {else}
            <button type="button" class="button1 js-bind">确认</button>
            {/if}
        </div>
       <!--  <div class="member-ts">
            <label>温馨提示</label>
            <p></p>
        </div> -->
</div>
<script type="text/javascript">
        var id = {$item.id};
        $(function () {
            //设置邮箱
            $('.js-bind').click(function () {
                var content = $('#content').val();
                if ($.trim(content) == "") {
                    message("请输入您需要回复的内容","","error");
                    return;
                }
                $.post(
                    '/home/feedback/save',
                    {content: content, parent_id: id},
                    function (ret) {
                        message(ret.message,ret.redirect,ret.type);
                    },'json'
                );
            });
        });
    </script>
</body>
</html>
