




<!DOCTYPE HTML>
<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>我的反馈</title>
    {include file='common/header'}
		<link rel="shortcut icon" href="clientapp/images/new_images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="/static/home/mobile/css/ydui.css"/>
    <link rel="stylesheet" href="/static/home/mobile/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/home/mobile/css/layui.css">
    <script type="text/javascript" src="/static/home/mobile/js/ydui.flexible.js"></script>

    

    <style>
        body{
            background: #F5F5F5 !important;
        }
        ul{margin-top:0.2rem;}
        ul>li{border-bottom: 1px solid #D9D9D9; background: #fff;padding:0.2rem 0.3rem;margin:0.1rem;border-radius:5px}
        b{text-align:right;display: block;    padding-bottom: 0.1rem;}
    </style>
</head>
<body>

<header class="m-navbar">
    <a href="javascript:history.back()" class="navbar-item">
        <i class="back-ico"></i>
    </a>
    <div class="navbar-center">
        <span class="navbar-title">我的反馈</span>
    </div>
    <a href="/home/feedback/add.html" class="navbar-item" >新增</a>
</header>
<div class="new-gold-detial">
    <div class="update-box mx_list" id="table">
        <ul id="flow">
        </ul>
        <!-- <div class="alipa-box">
            <div class="task-none" style="display: none;text-align: center;">暂无数据</div>
        </div> -->
    </div>
</div>
<script type="text/javascript" src="/static/home/mobile/js/layui/layui.js"></script>
<script type="text/javascript">
$(function(){
        //流加载
        layui.use('flow', function(){
            var flow = layui.flow;
            flow.load({
                    elem: '#table'
                    ,done: function(page, next){
                            var lis = [];
                            $.get('/home/feedback/ajax?page='+page, function(res){
                                layui.each(res.data.data, function(index, item){
                                    var status = item.is_reply == 1 ? '已回复' : '待回复';
                                    $("#flow").append('<li onclick="window.location.href=\'/home/feedback/detail/id/'+item.id+'.html\'"><b><span>'+item.create_time+"&nbsp;&nbsp;&nbsp;状态："+status+'</span></b><p><span>'+(item.content)+'</span></p></li>');
                                });
                                next(lis.join(''), res.data.length > 0 ? true : false);
                            });
                    }
            });
        });
});
</script>
</body>
</html>



