<!DOCTYPE HTML>
<html>
	<head>
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>推推推广平台用户中心</title>
		<link rel="shortcut icon" href="clientapp/images/new_images/favicon.ico" />
		<link href="/static/home/mobile/css/reset_5.css" rel="stylesheet" type="text/css" />
		<link href="/static/home/mobile/css/style.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" href="/static/home/mobile/css/font-awesome.min.css">
		<link href="/static/home/mobile/css/new_style.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" type="text/css" href="/static/home/mobile/css/ydui.css"/>
		<link rel="stylesheet" href="/static/home/mobile/css/mobile_comm.css">
        <!-- 弹出层 -->
        <link rel="stylesheet" href="/static/plugins/dialog/css/dialog.css" />
        <script src="/static/plugins/dialog/lib/zepto.min.js"></script>
        <script src="/static/plugins/dialog/js/dialog.js"></script>
    <script type="text/javascript" src="/static/home/mobile/js/ydui.flexible.js"></script>
        <!-- 弹出层 -->
        <script type="text/javascript" src="/static/plugins/clipboard.min.js"></script>
        <script type="text/javascript" src="/static/home/mobile/js/global.js"></script>
	</head>
	<style type="text/css">
		.site-header .tit-name {
			text-indent: -30px;
		}
		
		.site-header {
			padding-top: 20px;
		}
		
		.site-header .sc {
			top: 20px;
		}
		.site-header .member-intro{
			text-indent: 0;
		}
		.member-tx{
			margin-top: 10px;
		}
	</style>
	 <style type="text/css">
        .zhuanghu-tab li {
            width: 20%;
        }
        .task-list-remain-num span {
            width: 33.33%;
            float: left;
            text-align: center;
        }
        .paging {
            margin: 30px 0;
        }
        .dialog {
          position: fixed;
          left: 0;
          top: 0;
          z-index: 10001;
          width: 100%;
          height: 100%;
        }
        .dialog-content {
            width: 70%;
        }
        .dialog-overlay {
          position: absolute;
          top: 0;
          left: 0;
          z-index: 10002;
          width: 100%;
          height: 100%;
          background-color: rgba(0, 0, 0, 0.5);
		}
		.main{
			background-color: rgba(0, 0, 0, 0);
		}
		.m-cell{
			margin-bottom:0rem;
		}
    </style>

	<body>

	
		<div class="site-header user-center">
			<div class="tit-name">
				<div class="member-tx">
					<a href="/home/account/info.html">
                        <img src="{:to_media($member['avatar'])}" onerror="this.src='/static/home/mobile/picture/user.png'" style="width:94px;height:94px;margin: 0rem auto;">
                    </a>
				</div>
				<div id="accountName" style="font-size: 0.24rem;padding-top: 0.25rem;text-align: center;">欢迎{$member['nickname']?$member['nickname']:$member['username']}回家！           编号：{$member['uid']}</div>
				<div class="member-intro">
					<div id="level" class="level">V1</div>
					<span id="sign" style="color:#fff;">{$is_sign?'已签到':'签到'}</span>
				</div>
			</div>
			<a href="/home/account/info.html" class="sc"></a>
		</div>
		<div class="main accountCenter">
			<div class="m-cell">
				<div class="cell-item flex-ali">
					<div class="cell-left flex-ali">
						<img src="/static/home/mobile/images/yuenum.png" style="width:0.48rem;height:0.48rem;">
						&nbsp;&nbsp;<span id="gold">余额：{$member['credit2']?$member['credit2']:0}元</span>
					</div>
					<div class="cell-right center_blank">
						<a href="/home/recharge.html" >充值</a>&nbsp;&nbsp;
						|&nbsp;&nbsp;<a href="/home/account/withdraw.html" >取现</a>&nbsp;&nbsp;
						|&nbsp;&nbsp;<a href="/home/charge.html">流水</a>
					</div>
				</div>
				<div class="cell-item flex-ali center_blank">
					<img src="/static/home/mobile/images/integral.png" style="width:0.48rem;height:0.48rem;">&nbsp;&nbsp;
					<div class="cell-left flex-ali">积分：{$member['credit1']?$member['credit1']:0}</div>
					<a href="/home/account/credit.html" class="cell-right cell-arrow" >查看</a>
				</div>
			</div>

			<!-- <div class="jifen cl" style="margin: 0.2rem 0rem;">
				<div class="jf_one">
						<i class="jf_ico"><img src="/static/home/mobile/images/users_08.png"/></i>
						<div class="jf_desc">
							<a href="javascript:"  onclick="addmonth()">充值月会员</a>&nbsp;
							<a href="javascript:" onclick="aa(1)">充值年会员</a>
						</div>
				</div>
			</div> -->

			<div class="m-grids-3" style="margin: 0.2rem 0rem;" >
				<a href="/home/mytask.html" class="grids-item">
					<div class="grids-txt"><span>发布:{$task_num}</span></div>
				</a>
				<a href="/home/mytask/audit.html" class="grids-item">
					<div class="grids-txt"><span>审核:{$audit_num}</span></div>
				</a>
				<a href="/home/mytaskjoin.html" class="grids-item">
					<div class="grids-txt"><span>参与:{$join_num}</span></div>
				</a>
			</div>
			
			


			<div class="m-grids-2">
				<a href="/home/fans.html" class="grids-item">
					<div class="grids-txt flex-cen"><i class="icon-like"></i><span>粉丝关注</span></div>
				</a>
				<a href="/home/notice.html" class="grids-item">
					<div class="grids-txt flex-cen"><i class="icon-shield-outline"></i><span>公告</span></div>
				</a>
				<a href="/home/feedback.html" class="grids-item">
					<div class="grids-txt flex-cen"><i class="icon-feedback"></i><span>我的反馈</span></div>
				</a>
				<a href="{$site['qq']?$site['qq']:''}" class="grids-item">
					<div class="grids-txt flex-cen"><i class="icon-qq"></i><span>QQ群{$site['qq']}</span></div>
				</a>
				<a href="#" class="grids-item">
					<div class="grids-txt flex-cen">
					<i class="icon-weixin"></i>
					<span>微信客服</span>
					<span style="cursor: pointer" class="more-btn" data-copy="{$site['wechat']?$site['wechat']:''}" onclick="copy(this)">{$site['wechat']?$site['wechat']:''}</span>
					</div>
				</a>
				<a href="/home/help.html" class="grids-item">
					<div class="grids-txt flex-cen"><i class="icon-question"></i><span>新手引导</span></div>
				</a>
			</div>
			
			<!-- <div class="jifen cl clipboards">
				<div class="jf_one">
					<i class="jf_ico"><img src="/static/home/mobile/picture/qq1.png"/></i>
					<div class="jf_desc" style="display: block;width: 70%">
						<a href="" target="_blank" style="display: block;">
						QQ群
						</a>
					</div>
					<span style="cursor: pointer" class="more-btn" data-copy="{$site['qq']?$site['qq']:''}" onclick="copy(this)">{$site['qq']?$site['qq']:''}</span>
				</div>
			</div> -->
			<!-- <div class="jifen cl clipboards">
				<div class="jf_one">
					<i class="jf_ico"><img src="/static/home/mobile/picture/customer.png"/></i>
					<div class="jf_desc">
						微信客服
					</div>
					<span style="cursor: pointer" class="more-btn" data-copy="{$site['wechat']?$site['wechat']:''}" onclick="copy(this)">{$site['wechat']?$site['wechat']:''}</span>
				</div>
			</div> -->
			
		</div>
        <script type="text/javascript">
            $(function () {
                $('#sign').click(function () {
                    /*$.post(
                        window.location.href,
                        {},
                        function (res) {
                            message(res.message,res.redirect,res.type);
                        }
                    );*/
                    window.location.href = '/home/signin.html';
                });
            });
        </script>
        <script type="text/javascript">

function addmonth() {
    $(document).dialog({
        type : 'confirm',
        titleText: '确认操作',
        content: '确定升级为月会员吗?',
        onClickConfirmBtn: function(){
            Common.loading.show();
            $.post('/home/member/addMonthVip.html', function(res) {
                Common.loading.hide();
                if (res.type == "success") {
                    //$("#outStockTask" + id).addClass("ajax-ok").html("已下架");
                    //$("#outStockTask" + id).addClass("ajax-ok").html("已下架");
                    return;
                }
                message(res.message,res.redirect,res.type);
            });
        }
    });
}
		
        </script>
        {include file='common/footer'}
</body>
</html>