


<!DOCTYPE HTML>
<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>提现</title>
    {include file='common/header'}
    <link rel="shortcut icon" href="clientapp/images/new_images/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="/static/home/mobile/css/ydui.css"/>
        <link rel="stylesheet" href="/static/home/mobile/css/layui.css">
    <script type="text/javascript" src="/static/home/mobile/js/ydui.flexible.js"></script>

    <style>
        body{
            background: #F5F5F5 !important;
        }
        .user-gold{color:#0396FF;text-align: right;padding: 0.1rem 0.2rem;}
    </style>
</head>
<body>

<header class="m-navbar">
    <a href="javascript:history.back()" class="navbar-item">
        <i class="back-ico"></i>
    </a>
    <div class="navbar-center">
        <span class="navbar-title">提现</span>
    </div>
    <a href="withdrawlog.html" class="navbar-item" style="color: #fff;">明细</a>
</header>
<div class="new-top-up">
        <div class="update-box" id="hasZfb" style="">
            <form id="post_form">

                <div class="m-cell">
                    <div class="cell-item">
                        <div class="cell-left">账号：</div>
                        <div class="cell-right">
                            <input type="text" name="account" value="{$member['alipay_account']?$member['alipay_account']:''}" autocomplete="off" class="m_txt cell-input" placeholder="请输入手机号">
                        </div>
                    </div>
                    <div class="cell-item">
                        <label class="cell-right cell-arrow">
                            <select class="cell-select">
                                <option value="1" name="pay_method" >支付宝</option>
                                <option value="2" name="pay_method" >微信</option>
                                <option value="3" name="pay_method" >银行卡</option>
                            </select>
                        </label>
                    </div>
                    <div class="cell-item">
                        <div class="cell-left">姓名：</div>
                        <div class="cell-right">
                            <input type="text" name="realname" value="{$member['alipay_realname']?$member['alipay_realname']:''}" autocomplete="off" class="m_txt cell-input" placeholder="请输入真实姓名">
                        </div>
                    </div>
                    <div class="cell-item">
                        <div class="cell-left">手机号：</div>
                        <div class="cell-right">
                            <input type="text" name="mobile" value="{$member['mobile']?$member['mobile']:''}" autocomplete="off" class="m_txt cell-input" placeholder="请输入手机号">
                        </div>
                    </div>
                    <div class="cell-item">
                        <div class="cell-left">提现金额：</div>
                        <div class="cell-right">
                            <input type="number" class="m_txt cell-input" placeholder="请输入取现金额" name="credit2">
                        </div>
                    </div>
                    
                    <div class="user-gold">
                     <span>余额：￥{$member['credit2']?$member['credit2']:0}</span>
                    </div>
                    <div class="tixian_txt">
                        温馨提示：<br />
                        1、最低提现&nbsp;<span style="color: red">{$setting['withdraw_min']?$setting['withdraw_min']:0}</span>&nbsp;元，手续费&nbsp;<span style="color: red">{$setting['withdraw_fee']?$setting['withdraw_fee']:0}%</span>。<br />
                        2、提现时，系统将自动扣除<span style="color: red">{$setting['invitation_withdraw_rebate']?$setting['invitation_withdraw_rebate']:0}%</span>的红利给到你的推荐人，同样，你推荐的人在提现时一样返你<span style="color: red">{$setting['invitation_withdraw_rebate']?$setting['invitation_withdraw_rebate']:0}%</span>，推荐越多红利越多。<br />
                        3、每天可提现，&nbsp;<span style="color: red">24</span>&nbsp;小时到账
                    </div>
                    
                </div>
                <!-- <div class="zfb-count" style="display: flex;display: -webkit-flex;justify-content: space-around;align-items: center;">
                    <label>
                        <input name="pay_method" checked style="-webkit-appearance: radio" type="radio" value="1">支付宝
                    </label>
                    <label>
                        <input name="pay_method" style="-webkit-appearance: radio" type="radio" value="2">微信
                    </label>
                    <label>
                        <input name="pay_method" style="-webkit-appearance: radio" type="radio" value="0">银行卡
                    </label>
                </div>
                <div class="member-form">
                    <div class="item-box"><span>账号:</span>
                        <input type="text" name="account" value="{$member['alipay_account']?$member['alipay_account']:''}" class="m_txt" placeholder="请输入卡号、支付宝、微信账号">
                    </div>
                </div>
                <div class="member-form">
                    <div class="item-box"><span>姓名:</span>
                        <input type="text" name="realname" value="{$member['alipay_realname']?$member['alipay_realname']:''}" class="m_txt" placeholder="请输入真实姓名">
                    </div>
                </div>
                <div class="member-form">
                    <div class="item-box"><span>手机:</span>
                        <input type="text" name="mobile" class="m_txt" value="{$member['mobile']?$member['mobile']:''}" placeholder="请输入手机号">
                    </div>
                </div>

                <div class="member-form">
                    <div class="item-box"><span style="font-size: 21px;font-weight: bold">￥</span>
                        <input type="text" class="m_txt" placeholder="请输入取现金额" name="credit2">
                    </div>
                    <div class="tixian_txt">
                        温馨提示：<br />
                        1、最低提现&nbsp;<span style="color: red">{$setting['withdraw_min']?$setting['withdraw_min']:0}</span>&nbsp;元，手续费&nbsp;<span style="color: red">{$setting['withdraw_fee']?$setting['withdraw_fee']:0}%</span>。<br />
                        2、提现时，系统将自动扣除<span style="color: red">{$setting['invitation_withdraw_rebate']?$setting['invitation_withdraw_rebate']:0}%</span>的红利给到你的推荐人，同样，你推荐的人在提现时一样返你<span style="color: red">{$setting['invitation_withdraw_rebate']?$setting['invitation_withdraw_rebate']:0}%</span>，推荐越多红利越多。<br />
                        3、每天可提现，&nbsp;<span style="color: red">24</span>&nbsp;小时到账
                    </div>
                    <div class="member-btn">
                        <input type="button" class="button1" value="确认">
                    </div>
                </div> -->
                <div class="member-btn">
                        <input type="button" class="button1" value="确认">
                    </div>
            </form>
        </div>
    </div>
<script type="text/javascript" src="/static/home/mobile/js/layui/layui.js"></script>
<script type="text/javascript">
    $(function () {
            $('.button1').click(function () {
                $.post(
                    window.location.href,
                    $('#post_form').serialize(),
                    function (ret) {
                        message(ret.message,ret.redirect,ret.type);
                    },'json'
                );
            });
        });
</script>
</body>
</html>



